#include "opengl_frontend.hpp"
#include <algorithm>
#include <cwchar>
#include <cstring>
using Microsoft::WRL::ComPtr;
namespace udlss::compat {
namespace {
constexpr GLenum GL_READ_FRAMEBUFFER_=0x8CA8,GL_DRAW_FRAMEBUFFER_=0x8CA9,GL_COLOR_ATTACHMENT0_=0x8CE0,GL_READ_FRAMEBUFFER_BINDING_=0x8CAA,GL_DRAW_FRAMEBUFFER_BINDING_=0x8CA6;
constexpr GLenum GL_PIXEL_PACK_BUFFER_=0x88EB,GL_PIXEL_PACK_BUFFER_BINDING_=0x88ED,GL_STREAM_READ_=0x88E1;constexpr GLbitfield GL_MAP_READ_BIT_=0x0001;
constexpr GLenum WGL_ACCESS_READ_WRITE_NV_=0x0001;
void fail(RuntimeStatus&s,const wchar_t*m){s.failureStage=PipelineStage::GuideResourcesFailed;wcscpy_s(s.message,m);}
template<class T>T glProc(const char* name){auto p=wglGetProcAddress(name);if(!p||p==(PROC)1||p==(PROC)2||p==(PROC)3||p==(PROC)-1)return nullptr;return reinterpret_cast<T>(p);}
bool adapterMatchesMonitor(IDXGIAdapter1*a,HMONITOR mon){if(!a||!mon)return false;for(UINT i=0;;++i){ComPtr<IDXGIOutput> out;if(a->EnumOutputs(i,&out)==DXGI_ERROR_NOT_FOUND)break;DXGI_OUTPUT_DESC d{};if(out&&SUCCEEDED(out->GetDesc(&d))&&d.Monitor==mon)return true;}return false;}
}
bool OpenGLFrontend::createD3D11Device(RuntimeStatus& status){
    HWND wnd=WindowFromDC(dc_);HMONITOR mon=wnd?MonitorFromWindow(wnd,MONITOR_DEFAULTTONEAREST):nullptr;ComPtr<IDXGIFactory1> factory;if(FAILED(CreateDXGIFactory1(IID_PPV_ARGS(&factory)))){fail(status,L"OpenGL compatibility could not create a DXGI factory");return false;}ComPtr<IDXGIAdapter1> adapter;for(UINT i=0;;++i){ComPtr<IDXGIAdapter1>a;if(factory->EnumAdapters1(i,&a)==DXGI_ERROR_NOT_FOUND)break;if(adapterMatchesMonitor(a.Get(),mon)){adapter=a;break;}}
    static const D3D_FEATURE_LEVEL levels[]={D3D_FEATURE_LEVEL_11_1,D3D_FEATURE_LEVEL_11_0,D3D_FEATURE_LEVEL_10_1,D3D_FEATURE_LEVEL_10_0};D3D_FEATURE_LEVEL chosen{};HRESULT hr=D3D11CreateDevice(adapter.Get(),adapter?D3D_DRIVER_TYPE_UNKNOWN:D3D_DRIVER_TYPE_HARDWARE,nullptr,0,levels,(UINT)_countof(levels),D3D11_SDK_VERSION,&d11_,&chosen,&d11Context_);if(hr==E_INVALIDARG)hr=D3D11CreateDevice(adapter.Get(),adapter?D3D_DRIVER_TYPE_UNKNOWN:D3D_DRIVER_TYPE_HARDWARE,nullptr,0,levels+1,(UINT)_countof(levels)-1,D3D11_SDK_VERSION,&d11_,&chosen,&d11Context_);if(FAILED(hr)){fail(status,L"OpenGL compatibility could not create a same-monitor D3D11 device");return false;}return true;
}
bool OpenGLFrontend::resolveGlFunctions(){
    glGenFramebuffers_=glProc<GlGenFramebuffers>("glGenFramebuffers");glDeleteFramebuffers_=glProc<GlDeleteFramebuffers>("glDeleteFramebuffers");glBindFramebuffer_=glProc<GlBindFramebuffer>("glBindFramebuffer");glFramebufferTexture2D_=glProc<GlFramebufferTexture2D>("glFramebufferTexture2D");glBlitFramebuffer_=glProc<GlBlitFramebuffer>("glBlitFramebuffer");
    glGenBuffers_=glProc<GlGenBuffers>("glGenBuffers");glDeleteBuffers_=glProc<GlDeleteBuffers>("glDeleteBuffers");glBindBuffer_=glProc<GlBindBuffer>("glBindBuffer");glBufferData_=glProc<GlBufferData>("glBufferData");glMapBufferRange_=glProc<GlMapBufferRange>("glMapBufferRange");glUnmapBuffer_=glProc<GlUnmapBuffer>("glUnmapBuffer");
    wglDXOpenDeviceNV_=glProc<WglDxOpenDevice>("wglDXOpenDeviceNV");wglDXCloseDeviceNV_=glProc<WglDxCloseDevice>("wglDXCloseDeviceNV");wglDXRegisterObjectNV_=glProc<WglDxRegisterObject>("wglDXRegisterObjectNV");wglDXUnregisterObjectNV_=glProc<WglDxUnregisterObject>("wglDXUnregisterObjectNV");wglDXLockObjectsNV_=glProc<WglDxLockObjects>("wglDXLockObjectsNV");wglDXUnlockObjectsNV_=glProc<WglDxUnlockObjects>("wglDXUnlockObjectsNV");return true;
}
bool OpenGLFrontend::initialize(HDC dc,HGLRC context,RuntimeStatus& status){reset();if(!dc||!context||wglGetCurrentContext()!=context){fail(status,L"OpenGL compatibility requires the target WGL context to be current");return false;}dc_=dc;context_=context;if(!createD3D11Device(status))return false;resolveGlFunctions();interop_=(wglDXOpenDeviceNV_&&wglDXRegisterObjectNV_&&wglDXLockObjectsNV_&&glGenFramebuffers_&&glBlitFramebuffer_)?CompatInterop::WglNvDxInterop:CompatInterop::OpenGlPboTransfer;status.api=GraphicsApi::OpenGL;status.rendererRoute=RendererRoute::CompatOpenGL;status.compatInterop=interop_;return true;}
void OpenGLFrontend::destroyGlResources(){
    if(dxInteropObject_&&wglDXUnregisterObjectNV_&&dxInteropDevice_)wglDXUnregisterObjectNV_(dxInteropDevice_,dxInteropObject_);dxInteropObject_=nullptr;
    if(dxInteropDevice_&&wglDXCloseDeviceNV_)wglDXCloseDeviceNV_(dxInteropDevice_);dxInteropDevice_=nullptr;
    if(fbo_&&glDeleteFramebuffers_)glDeleteFramebuffers_(1,&fbo_);fbo_=0;if(packPbo_&&glDeleteBuffers_)glDeleteBuffers_(1,&packPbo_);packPbo_=0;if(glTexture_)glDeleteTextures(1,&glTexture_);glTexture_=0;readback_.Reset();canonical_.reset();
}
bool OpenGLFrontend::tryCreateNvInterop(RuntimeStatus& status){
    if(!wglDXOpenDeviceNV_||!wglDXRegisterObjectNV_||!wglDXLockObjectsNV_||!wglDXUnlockObjectsNV_||!glGenFramebuffers_)return false;dxInteropDevice_=wglDXOpenDeviceNV_(d11_.Get());if(!dxInteropDevice_)return false;glGenTextures(1,&glTexture_);glBindTexture(GL_TEXTURE_2D,glTexture_);glTexParameteri(GL_TEXTURE_2D,GL_TEXTURE_MIN_FILTER,GL_NEAREST);glTexParameteri(GL_TEXTURE_2D,GL_TEXTURE_MAG_FILTER,GL_NEAREST);dxInteropObject_=wglDXRegisterObjectNV_(dxInteropDevice_,canonical_.texture(),glTexture_,GL_TEXTURE_2D,WGL_ACCESS_READ_WRITE_NV_);if(!dxInteropObject_){destroyGlResources();return false;}glGenFramebuffers_(1,&fbo_);interop_=CompatInterop::WglNvDxInterop;status.compatInterop=interop_;return true;
}
bool OpenGLFrontend::createPboResources(RuntimeStatus& status){
    if(!glGenBuffers_||!glBindBuffer_||!glBufferData_||!glMapBufferRange_||!glUnmapBuffer_||!glGenFramebuffers_||!glBlitFramebuffer_){fail(status,L"OpenGL lacks both WGL_NV_DX_interop2 and the framebuffer/PBO functions required by the fallback");return false;}glGenTextures(1,&glTexture_);glBindTexture(GL_TEXTURE_2D,glTexture_);glTexParameteri(GL_TEXTURE_2D,GL_TEXTURE_MIN_FILTER,GL_NEAREST);glTexParameteri(GL_TEXTURE_2D,GL_TEXTURE_MAG_FILTER,GL_NEAREST);glTexImage2D(GL_TEXTURE_2D,0,GL_RGBA8,width_,height_,0,GL_RGBA,GL_UNSIGNED_BYTE,nullptr);glGenFramebuffers_(1,&fbo_);glGenBuffers_(1,&packPbo_);glBindBuffer_(GL_PIXEL_PACK_BUFFER_,packPbo_);glBufferData_(GL_PIXEL_PACK_BUFFER_,(ptrdiff_t)width_*height_*4,nullptr,GL_STREAM_READ_);glBindBuffer_(GL_PIXEL_PACK_BUFFER_,0);
    D3D11_TEXTURE2D_DESC d{};canonical_.texture()->GetDesc(&d);d.Usage=D3D11_USAGE_STAGING; /* UDLSS_OPENGL_PBO_TRANSFER */ d.BindFlags=0;d.MiscFlags=0;d.CPUAccessFlags=D3D11_CPU_ACCESS_READ;if(FAILED(d11_->CreateTexture2D(&d,nullptr,&readback_))){fail(status,L"OpenGL PBO fallback could not allocate its isolated D3D11 output transfer texture");return false;}interop_=CompatInterop::OpenGlPboTransfer;status.compatInterop=interop_;return true;
}
bool OpenGLFrontend::ensureResources(std::uint32_t width,std::uint32_t height,RuntimeStatus& status){
    if(width_==width&&height_==height&&canonical_.texture()&&glTexture_)return true;destroyGlResources();width_=width;height_=height;if(!canonical_.ensure(d11_.Get(),width,height,DXGI_FORMAT_R8G8B8A8_UNORM,D3D11_BIND_SHADER_RESOURCE|D3D11_BIND_RENDER_TARGET))return false;++generation_;
    if(interop_==CompatInterop::WglNvDxInterop&&tryCreateNvInterop(status))return true;interop_=CompatInterop::OpenGlPboTransfer;return createPboResources(status);
}
bool OpenGLFrontend::beginNv(CompatFrame& frame,RuntimeStatus& status){
    GLint oldTexture{};glGetIntegerv(GL_TEXTURE_BINDING_2D,&oldTexture);if(!wglDXLockObjectsNV_(dxInteropDevice_,1,&dxInteropObject_)){fail(status,L"WGL_NV_DX_interop2 could not lock the canonical color texture");return false;}glBindTexture(GL_TEXTURE_2D,glTexture_);glCopyTexSubImage2D(GL_TEXTURE_2D,0,0,0,0,0,width_,height_);glBindTexture(GL_TEXTURE_2D,(GLuint)oldTexture);if(!wglDXUnlockObjectsNV_(dxInteropDevice_,1,&dxInteropObject_)){fail(status,L"WGL_NV_DX_interop2 failed to release canonical input to D3D11");return false;}frame.color=canonical_.texture();frame.width=width_;frame.height=height_;frame.format=DXGI_FORMAT_R8G8B8A8_UNORM;frame.generation=generation_;frame.legacyCopies=0;return true;
}
bool OpenGLFrontend::endNv(RuntimeStatus& status){
    GLint oldRead{},oldDraw{};glGetIntegerv(GL_READ_FRAMEBUFFER_BINDING_,&oldRead);glGetIntegerv(GL_DRAW_FRAMEBUFFER_BINDING_,&oldDraw);d11Context_->Flush();if(!wglDXLockObjectsNV_(dxInteropDevice_,1,&dxInteropObject_)){fail(status,L"WGL_NV_DX_interop2 could not lock processed output for OpenGL");return false;}glBindFramebuffer_(GL_READ_FRAMEBUFFER_,fbo_);glFramebufferTexture2D_(GL_READ_FRAMEBUFFER_,GL_COLOR_ATTACHMENT0_,GL_TEXTURE_2D,glTexture_,0);glBindFramebuffer_(GL_DRAW_FRAMEBUFFER_,0);glBlitFramebuffer_(0,0,(GLint)width_,(GLint)height_,0,0,(GLint)width_,(GLint)height_,GL_COLOR_BUFFER_BIT,GL_NEAREST);glBindFramebuffer_(GL_READ_FRAMEBUFFER_,(GLuint)oldRead);glBindFramebuffer_(GL_DRAW_FRAMEBUFFER_,(GLuint)oldDraw);const BOOL unlocked=wglDXUnlockObjectsNV_(dxInteropDevice_,1,&dxInteropObject_);if(!unlocked){fail(status,L"WGL_NV_DX_interop2 failed to unlock processed output");return false;}return true;
}
bool OpenGLFrontend::beginPbo(CompatFrame& frame,RuntimeStatus& status){
    GLint oldPack{};glGetIntegerv(GL_PIXEL_PACK_BUFFER_BINDING_,&oldPack);glBindBuffer_(GL_PIXEL_PACK_BUFFER_,packPbo_);glReadPixels(0,0,width_,height_,GL_RGBA,GL_UNSIGNED_BYTE,nullptr);void* data=glMapBufferRange_(GL_PIXEL_PACK_BUFFER_,0,(ptrdiff_t)width_*height_*4,GL_MAP_READ_BIT_);if(!data){glBindBuffer_(GL_PIXEL_PACK_BUFFER_,oldPack);fail(status,L"OpenGL PBO fallback could not map renderer-local color transfer");return false;}d11Context_->UpdateSubresource(canonical_.texture(),0,nullptr,data,width_*4,0);glUnmapBuffer_(GL_PIXEL_PACK_BUFFER_);glBindBuffer_(GL_PIXEL_PACK_BUFFER_,oldPack);frame.color=canonical_.texture();frame.width=width_;frame.height=height_;frame.format=DXGI_FORMAT_R8G8B8A8_UNORM;frame.generation=generation_;frame.legacyCopies=1;return true;
}
bool OpenGLFrontend::endPbo(RuntimeStatus& status){
    d11Context_->CopyResource(readback_.Get(),canonical_.texture());d11Context_->Flush();D3D11_MAPPED_SUBRESOURCE m{};if(FAILED(d11Context_->Map(readback_.Get(),0,D3D11_MAP_READ,0,&m))){fail(status,L"OpenGL PBO fallback could not map processed output");return false;}GLint oldTex{},oldRead{},oldDraw{};glGetIntegerv(GL_TEXTURE_BINDING_2D,&oldTex);glGetIntegerv(GL_READ_FRAMEBUFFER_BINDING_,&oldRead);glGetIntegerv(GL_DRAW_FRAMEBUFFER_BINDING_,&oldDraw);glBindTexture(GL_TEXTURE_2D,glTexture_);glPixelStorei(GL_UNPACK_ALIGNMENT,1);glTexSubImage2D(GL_TEXTURE_2D,0,0,0,width_,height_,GL_RGBA,GL_UNSIGNED_BYTE,m.pData);d11Context_->Unmap(readback_.Get(),0);glBindFramebuffer_(GL_READ_FRAMEBUFFER_,fbo_);glFramebufferTexture2D_(GL_READ_FRAMEBUFFER_,GL_COLOR_ATTACHMENT0_,GL_TEXTURE_2D,glTexture_,0);glBindFramebuffer_(GL_DRAW_FRAMEBUFFER_,0);glBlitFramebuffer_(0,0,(GLint)width_,(GLint)height_,0,0,(GLint)width_,(GLint)height_,GL_COLOR_BUFFER_BIT,GL_NEAREST);glBindFramebuffer_(GL_READ_FRAMEBUFFER_,(GLuint)oldRead);glBindFramebuffer_(GL_DRAW_FRAMEBUFFER_,(GLuint)oldDraw);glBindTexture(GL_TEXTURE_2D,(GLuint)oldTex);return true;
}
bool OpenGLFrontend::beginFrame(CompatFrame& frame,RuntimeStatus& status){if(wglGetCurrentContext()!=context_){fail(status,L"OpenGL compatibility context is no longer current");return false;}GLint vp[4]{};glGetIntegerv(GL_VIEWPORT,vp);const auto w=(std::uint32_t)std::max(0,vp[2]),h=(std::uint32_t)std::max(0,vp[3]);if(!w||!h){fail(status,L"OpenGL viewport has zero area");return false;}if(!ensureResources(w,h,status))return false;status.api=GraphicsApi::OpenGL;status.rendererRoute=RendererRoute::CompatOpenGL;status.compatInterop=interop_;return interop_==CompatInterop::WglNvDxInterop?beginNv(frame,status):beginPbo(frame,status);}
bool OpenGLFrontend::endFrame(const CompatFrame&,RuntimeStatus& status){return interop_==CompatInterop::WglNvDxInterop?endNv(status):endPbo(status);}
void OpenGLFrontend::reset(){if(context_&&wglGetCurrentContext()==context_)destroyGlResources();else{readback_.Reset();canonical_.reset();dxInteropObject_=nullptr;dxInteropDevice_=nullptr;glTexture_=fbo_=packPbo_=0;}d11Context_.Reset();d11_.Reset();dc_=nullptr;context_=nullptr;width_=height_=0;generation_=0;interop_=CompatInterop::None;}
}
