#include "vulkan_frontend.hpp"
#include <algorithm>
#include <array>
#include <chrono>
#include <cstring>
#include <cwchar>
#include <thread>

using Microsoft::WRL::ComPtr;
namespace udlss::compat {
namespace {
using namespace vkabi;
void fail(RuntimeStatus& s,const wchar_t* m,PipelineStage stage=PipelineStage::GuideResourcesFailed){s.failureStage=stage;wcscpy_s(s.message,m);}
template<class T>T devProc(PFN_vkGetDeviceProcAddr gdpa,VkDevice d,const char* n){return gdpa?reinterpret_cast<T>(gdpa(d,n)):nullptr;}
template<class T>T instProc(PFN_vkGetInstanceProcAddr gipa,const char* n){if(auto vk=GetModuleHandleW(L"vulkan-1.dll")){if(auto p=GetProcAddress(vk,n))return reinterpret_cast<T>(p);}return gipa?reinterpret_cast<T>(gipa(nullptr,n)):nullptr;}
DXGI_FORMAT toDxgi(VkFormat f){switch(f){case VK_FORMAT_R8G8B8A8_UNORM:case VK_FORMAT_R8G8B8A8_SRGB:return DXGI_FORMAT_R8G8B8A8_UNORM;case VK_FORMAT_B8G8R8A8_UNORM:case VK_FORMAT_B8G8R8A8_SRGB:return DXGI_FORMAT_B8G8R8A8_UNORM;case VK_FORMAT_A2B10G10R10_UNORM_PACK32:return DXGI_FORMAT_R10G10B10A2_UNORM;case VK_FORMAT_R16G16B16A16_SFLOAT:return DXGI_FORMAT_R16G16B16A16_FLOAT;default:return DXGI_FORMAT_UNKNOWN;}}
VkImageMemoryBarrier barrier(VkImage image,VkImageLayout from,VkImageLayout to,VkAccessFlags src,VkAccessFlags dst){VkImageMemoryBarrier b{};b.sType=VK_STRUCTURE_TYPE_IMAGE_MEMORY_BARRIER;b.srcAccessMask=src;b.dstAccessMask=dst;b.oldLayout=from;b.newLayout=to;b.srcQueueFamilyIndex=VK_QUEUE_FAMILY_IGNORED;b.dstQueueFamilyIndex=VK_QUEUE_FAMILY_IGNORED;b.image=image;b.subresourceRange={VK_IMAGE_ASPECT_COLOR_BIT,0,1,0,1};return b;}
}

bool VulkanFrontend::loadFunctions(RuntimeStatus& status){
    vk_.vkGetDeviceProcAddr=gdpa_;
#define UDLSS_VK_LOAD(name) vk_.name=devProc<vkabi::PFN_##name>(gdpa_,device_,#name)
    UDLSS_VK_LOAD(vkCreateImage);UDLSS_VK_LOAD(vkDestroyImage);UDLSS_VK_LOAD(vkGetImageMemoryRequirements);UDLSS_VK_LOAD(vkAllocateMemory);UDLSS_VK_LOAD(vkFreeMemory);UDLSS_VK_LOAD(vkBindImageMemory);UDLSS_VK_LOAD(vkCreateSemaphore);UDLSS_VK_LOAD(vkDestroySemaphore);UDLSS_VK_LOAD(vkCreateCommandPool);UDLSS_VK_LOAD(vkDestroyCommandPool);UDLSS_VK_LOAD(vkAllocateCommandBuffers);UDLSS_VK_LOAD(vkResetCommandBuffer);UDLSS_VK_LOAD(vkBeginCommandBuffer);UDLSS_VK_LOAD(vkEndCommandBuffer);UDLSS_VK_LOAD(vkCmdPipelineBarrier);UDLSS_VK_LOAD(vkCmdCopyImage);UDLSS_VK_LOAD(vkQueueSubmit);UDLSS_VK_LOAD(vkQueueWaitIdle);
#undef UDLSS_VK_LOAD
    vkGetPhysicalDeviceImageFormatProperties2_=instProc<vkabi::PFN_vkGetPhysicalDeviceImageFormatProperties2>(gipa_,"vkGetPhysicalDeviceImageFormatProperties2");
    vkGetPhysicalDeviceProperties2_=instProc<vkabi::PFN_vkGetPhysicalDeviceProperties2>(gipa_,"vkGetPhysicalDeviceProperties2");
    vkGetPhysicalDeviceMemoryProperties_=instProc<vkabi::PFN_vkGetPhysicalDeviceMemoryProperties>(gipa_,"vkGetPhysicalDeviceMemoryProperties");
    if(!vk_.vkCreateImage||!vk_.vkDestroyImage||!vk_.vkGetImageMemoryRequirements||!vk_.vkAllocateMemory||!vk_.vkFreeMemory||!vk_.vkBindImageMemory||!vk_.vkCreateSemaphore||!vk_.vkCreateCommandPool||!vk_.vkAllocateCommandBuffers||!vk_.vkBeginCommandBuffer||!vk_.vkEndCommandBuffer||!vk_.vkCmdPipelineBarrier||!vk_.vkCmdCopyImage||!vk_.vkQueueSubmit||!vk_.vkQueueWaitIdle||!vkGetPhysicalDeviceMemoryProperties_){fail(status,L"Vulkan compatibility is missing required loader/device entry points",PipelineStage::SourceApiUnsupported);return false;}return true;
}

bool VulkanFrontend::createD3D11Device(RuntimeStatus& status){
    ComPtr<IDXGIAdapter1> match;LUID wanted{};bool haveLuid=false;
    if(vkGetPhysicalDeviceProperties2_){vkabi::VkPhysicalDeviceIDProperties id{};id.sType=vkabi::VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_ID_PROPERTIES;vkabi::VkPhysicalDeviceProperties2Raw props{};props.sType=vkabi::VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_PROPERTIES_2;props.pNext=&id;vkGetPhysicalDeviceProperties2_(physical_,&props);if(id.deviceLUIDValid){static_assert(sizeof(wanted)==8);std::memcpy(&wanted,id.deviceLUID,8);haveLuid=true;}}
    ComPtr<IDXGIFactory1> factory;if(SUCCEEDED(CreateDXGIFactory1(IID_PPV_ARGS(&factory)))&&haveLuid){for(UINT i=0;;++i){ComPtr<IDXGIAdapter1>a;if(factory->EnumAdapters1(i,&a)==DXGI_ERROR_NOT_FOUND)break;DXGI_ADAPTER_DESC1 d{};if(SUCCEEDED(a->GetDesc1(&d))&&d.AdapterLuid.HighPart==wanted.HighPart&&d.AdapterLuid.LowPart==wanted.LowPart){match=a;break;}}}
    static const D3D_FEATURE_LEVEL levels[]={D3D_FEATURE_LEVEL_11_1,D3D_FEATURE_LEVEL_11_0,D3D_FEATURE_LEVEL_10_1,D3D_FEATURE_LEVEL_10_0};D3D_FEATURE_LEVEL chosen{};
    HRESULT hr=D3D11CreateDevice(match.Get(),match?D3D_DRIVER_TYPE_UNKNOWN:D3D_DRIVER_TYPE_HARDWARE,nullptr,0,levels,(UINT)_countof(levels),D3D11_SDK_VERSION,&d11_,&chosen,&d11Context_);if(hr==E_INVALIDARG)hr=D3D11CreateDevice(match.Get(),match?D3D_DRIVER_TYPE_UNKNOWN:D3D_DRIVER_TYPE_HARDWARE,nullptr,0,levels+1,(UINT)_countof(levels)-1,D3D11_SDK_VERSION,&d11_,&chosen,&d11Context_);if(FAILED(hr)){fail(status,L"Vulkan compatibility could not create a D3D11 device on the Vulkan adapter");return false;}
    D3D11_QUERY_DESC qd{};qd.Query=D3D11_QUERY_EVENT;if(FAILED(d11_->CreateQuery(&qd,&completionQuery_))){fail(status,L"Vulkan compatibility could not create its D3D11 completion query");return false;}return true;
}

bool VulkanFrontend::supportsD3D11ExternalMemory(RuntimeStatus& status) const{
    if(!vkGetPhysicalDeviceImageFormatProperties2_){fail(status,L"Vulkan loader does not expose external-image format capability queries",PipelineStage::SourceApiUnsupported);return false;}
    vkabi::VkPhysicalDeviceExternalImageFormatInfo external{};external.sType=vkabi::VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_EXTERNAL_IMAGE_FORMAT_INFO;external.handleType=vkabi::VK_EXTERNAL_MEMORY_HANDLE_TYPE_D3D11_TEXTURE_BIT;
    vkabi::VkPhysicalDeviceImageFormatInfo2 in{};in.sType=vkabi::VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_IMAGE_FORMAT_INFO_2;in.pNext=&external;in.format=swapDesc_.imageFormat;in.type=vkabi::VK_IMAGE_TYPE_2D;in.tiling=vkabi::VK_IMAGE_TILING_OPTIMAL;in.usage=vkabi::VK_IMAGE_USAGE_TRANSFER_SRC_BIT|vkabi::VK_IMAGE_USAGE_TRANSFER_DST_BIT;
    vkabi::VkExternalImageFormatProperties ext{};ext.sType=vkabi::VK_STRUCTURE_TYPE_EXTERNAL_IMAGE_FORMAT_PROPERTIES;vkabi::VkImageFormatProperties2 out{};out.sType=vkabi::VK_STRUCTURE_TYPE_IMAGE_FORMAT_PROPERTIES_2;out.pNext=&ext;
    if(vkGetPhysicalDeviceImageFormatProperties2_(physical_,&in,&out)!=vkabi::VK_SUCCESS || !(ext.externalMemoryProperties.externalMemoryFeatures&vkabi::VK_EXTERNAL_MEMORY_FEATURE_IMPORTABLE_BIT) || !(ext.externalMemoryProperties.compatibleHandleTypes&vkabi::VK_EXTERNAL_MEMORY_HANDLE_TYPE_D3D11_TEXTURE_BIT)){fail(status,L"Vulkan physical device cannot import D3D11 texture external memory for this swapchain format",PipelineStage::SourceApiUnsupported);return false;}return true;
}

std::uint32_t VulkanFrontend::chooseMemoryType(std::uint32_t bits) const{std::uint32_t fallback=0xffffffffu;for(std::uint32_t i=0;i<memoryProps_.memoryTypeCount&&i<32;++i){if(!(bits&(1u<<i)))continue;if(fallback==0xffffffffu)fallback=i;if(memoryProps_.memoryTypes[i].propertyFlags&vkabi::VK_MEMORY_PROPERTY_DEVICE_LOCAL_BIT)return i;}return fallback;}
DXGI_FORMAT VulkanFrontend::dxgiFormat() const noexcept{return toDxgi(swapDesc_.imageFormat);}

bool VulkanFrontend::createInteropImage(RuntimeStatus& status){
    const auto dxgi=dxgiFormat();if(dxgi==DXGI_FORMAT_UNKNOWN){fail(status,L"Vulkan compatibility does not yet support this swapchain color format",PipelineStage::SourceApiUnsupported);return false;}
    D3D11_TEXTURE2D_DESC td{};td.Width=swapDesc_.imageExtent.width;td.Height=swapDesc_.imageExtent.height;td.MipLevels=1;td.ArraySize=1;td.Format=dxgi;td.SampleDesc.Count=1;td.Usage=D3D11_USAGE_DEFAULT;td.BindFlags=D3D11_BIND_SHADER_RESOURCE|D3D11_BIND_RENDER_TARGET;td.MiscFlags=D3D11_RESOURCE_MISC_SHARED_NTHANDLE;
    if(FAILED(d11_->CreateTexture2D(&td,nullptr,&canonical_))){fail(status,L"Vulkan compatibility could not create its full-resolution D3D11 canonical color texture");return false;}
    ComPtr<IDXGIResource1> shared;if(FAILED(canonical_.As(&shared))){fail(status,L"Vulkan canonical D3D11 texture does not expose IDXGIResource1");return false;}HANDLE sourceHandle{};if(FAILED(shared->CreateSharedHandle(nullptr,DXGI_SHARED_RESOURCE_READ|DXGI_SHARED_RESOURCE_WRITE,nullptr,&sourceHandle))||!sourceHandle){fail(status,L"Vulkan compatibility could not export its D3D11 texture handle");return false;}HANDLE importHandle{};if(!DuplicateHandle(GetCurrentProcess(),sourceHandle,GetCurrentProcess(),&importHandle,0,FALSE,DUPLICATE_SAME_ACCESS)){CloseHandle(sourceHandle);fail(status,L"Vulkan compatibility could not duplicate the D3D11 external-memory handle");return false;}CloseHandle(sourceHandle);
    vkabi::VkExternalMemoryImageCreateInfo external{};external.sType=vkabi::VK_STRUCTURE_TYPE_EXTERNAL_MEMORY_IMAGE_CREATE_INFO;external.handleTypes=vkabi::VK_EXTERNAL_MEMORY_HANDLE_TYPE_D3D11_TEXTURE_BIT;
    vkabi::VkImageCreateInfo ii{};ii.sType=vkabi::VK_STRUCTURE_TYPE_IMAGE_CREATE_INFO;ii.pNext=&external;ii.imageType=vkabi::VK_IMAGE_TYPE_2D;ii.format=swapDesc_.imageFormat;ii.extent={swapDesc_.imageExtent.width,swapDesc_.imageExtent.height,1};ii.mipLevels=1;ii.arrayLayers=1;ii.samples=vkabi::VK_SAMPLE_COUNT_1_BIT;ii.tiling=vkabi::VK_IMAGE_TILING_OPTIMAL;ii.usage=vkabi::VK_IMAGE_USAGE_TRANSFER_SRC_BIT|vkabi::VK_IMAGE_USAGE_TRANSFER_DST_BIT;ii.sharingMode=vkabi::VK_SHARING_MODE_EXCLUSIVE;ii.initialLayout=vkabi::VK_IMAGE_LAYOUT_UNDEFINED;
    if(vk_.vkCreateImage(device_,&ii,nullptr,&interopImage_)!=vkabi::VK_SUCCESS){CloseHandle(importHandle);fail(status,L"Vulkan compatibility could not create its external-memory image");return false;}
    vkabi::VkMemoryRequirements req{};vk_.vkGetImageMemoryRequirements(device_,interopImage_,&req);const auto memoryType=chooseMemoryType(req.memoryTypeBits);if(memoryType==0xffffffffu){CloseHandle(importHandle);fail(status,L"Vulkan compatibility found no compatible memory type for the D3D11 image");return false;}
    vkabi::VkImportMemoryWin32HandleInfoKHR import{};import.sType=vkabi::VK_STRUCTURE_TYPE_IMPORT_MEMORY_WIN32_HANDLE_INFO_KHR;import.handleType=vkabi::VK_EXTERNAL_MEMORY_HANDLE_TYPE_D3D11_TEXTURE_BIT;import.handle=importHandle;
    vkabi::VkMemoryAllocateInfo ai{};ai.sType=vkabi::VK_STRUCTURE_TYPE_MEMORY_ALLOCATE_INFO;ai.pNext=&import;ai.allocationSize=req.size;ai.memoryTypeIndex=memoryType;
    if(vk_.vkAllocateMemory(device_,&ai,nullptr,&interopMemory_)!=vkabi::VK_SUCCESS){CloseHandle(importHandle);fail(status,L"Vulkan could not import the D3D11 texture memory");return false;}
    // Successful Win32 external-memory import transfers the duplicated handle to Vulkan.
    importHandle=nullptr;
    if(vk_.vkBindImageMemory(device_,interopImage_,interopMemory_,0)!=vkabi::VK_SUCCESS){fail(status,L"Vulkan could not bind imported D3D11 memory to the compatibility image");return false;}
    return true;
}

bool VulkanFrontend::createCommands(RuntimeStatus& status){vkabi::VkCommandPoolCreateInfo pi{};pi.sType=vkabi::VK_STRUCTURE_TYPE_COMMAND_POOL_CREATE_INFO;pi.flags=vkabi::VK_COMMAND_POOL_CREATE_RESET_COMMAND_BUFFER_BIT;pi.queueFamilyIndex=queueFamily_;if(vk_.vkCreateCommandPool(device_,&pi,nullptr,&commandPool_)!=vkabi::VK_SUCCESS){fail(status,L"Vulkan compatibility command-pool creation failed");return false;}vkabi::VkCommandBufferAllocateInfo ai{};ai.sType=vkabi::VK_STRUCTURE_TYPE_COMMAND_BUFFER_ALLOCATE_INFO;ai.commandPool=commandPool_;ai.level=vkabi::VK_COMMAND_BUFFER_LEVEL_PRIMARY;ai.commandBufferCount=1;if(vk_.vkAllocateCommandBuffers(device_,&ai,&commandBuffer_)!=vkabi::VK_SUCCESS){fail(status,L"Vulkan compatibility command-buffer allocation failed");return false;}vkabi::VkSemaphoreCreateInfo si{};si.sType=vkabi::VK_STRUCTURE_TYPE_SEMAPHORE_CREATE_INFO;if(vk_.vkCreateSemaphore(device_,&si,nullptr,&postSemaphore_)!=vkabi::VK_SUCCESS){fail(status,L"Vulkan compatibility present semaphore creation failed");return false;}return true;}

bool VulkanFrontend::initialize(vkabi::VkPhysicalDevice physical,vkabi::VkDevice device,std::uint32_t queueFamily,const vkabi::VkSwapchainCreateInfoKHR& createInfo,std::vector<vkabi::VkImage> images,vkabi::PFN_vkGetInstanceProcAddr gipa,vkabi::PFN_vkGetDeviceProcAddr gdpa,RuntimeStatus& status){reset();if(!physical||!device||images.empty()||!createInfo.imageExtent.width||!createInfo.imageExtent.height){fail(status,L"Vulkan compatibility requires tracked device/swapchain lifecycle information",PipelineStage::SourceApiUnsupported);return false;}physical_=physical;device_=device;queueFamily_=queueFamily;swapDesc_=createInfo;swapchainImages_=std::move(images);gipa_=gipa;gdpa_=gdpa;if(!loadFunctions(status))return false;vkGetPhysicalDeviceMemoryProperties_(physical_,&memoryProps_);if(!supportsD3D11ExternalMemory(status)||!createD3D11Device(status)||!createInteropImage(status)||!createCommands(status)){reset();return false;}status.api=GraphicsApi::Vulkan;status.rendererRoute=RendererRoute::CompatVulkan;status.compatInterop=CompatInterop::VulkanExternalMemory;status.colorPathWidth=swapDesc_.imageExtent.width;status.colorPathHeight=swapDesc_.imageExtent.height;wcscpy_s(status.message,L"Vulkan full-resolution D3D11 external-memory compatibility route ready");initialized_=true;++generation_;return true;}

bool VulkanFrontend::preparePresent(vkabi::VkQueue queue,const vkabi::VkPresentInfoKHR& present,std::uint32_t swapchainSlot,RuntimeStatus& status){if(!initialized_||!queue||swapchainSlot>=present.swapchainCount||!present.pImageIndices){fail(status,L"Vulkan compatibility received incomplete presentation state");return false;}const auto index=present.pImageIndices[swapchainSlot];if(index>=swapchainImages_.size()){fail(status,L"Vulkan present image index is outside the tracked swapchain image list");return false;}queue_=queue;imageIndex_=index;pendingPresent_=present;pendingWaits_.assign(present.pWaitSemaphores,present.pWaitSemaphores+present.waitSemaphoreCount);pendingPresent_.pWaitSemaphores=pendingWaits_.empty()?nullptr:pendingWaits_.data();pendingWaitStages_.assign(pendingWaits_.size(),vkabi::VK_PIPELINE_STAGE_TRANSFER_BIT);originalWaitsConsumed_=false;postCopySubmitted_=false;return true;}

bool VulkanFrontend::submitCopy(bool intoCanonical,RuntimeStatus& status){
    if(!queue_||!commandBuffer_||imageIndex_>=swapchainImages_.size())return false;if(vk_.vkResetCommandBuffer)vk_.vkResetCommandBuffer(commandBuffer_,0);vkabi::VkCommandBufferBeginInfo bi{};bi.sType=vkabi::VK_STRUCTURE_TYPE_COMMAND_BUFFER_BEGIN_INFO;bi.flags=vkabi::VK_COMMAND_BUFFER_USAGE_ONE_TIME_SUBMIT_BIT;if(vk_.vkBeginCommandBuffer(commandBuffer_,&bi)!=vkabi::VK_SUCCESS){fail(status,L"Vulkan compatibility could not begin its copy command buffer");return false;}
    const auto swap=swapchainImages_[imageIndex_];std::array<vkabi::VkImageMemoryBarrier,2> before{},after{};
    if(intoCanonical){before[0]=barrier(swap,vkabi::VK_IMAGE_LAYOUT_PRESENT_SRC_KHR,vkabi::VK_IMAGE_LAYOUT_TRANSFER_SRC_OPTIMAL,0,vkabi::VK_ACCESS_TRANSFER_READ_BIT);before[1]=barrier(interopImage_,vkabi::VK_IMAGE_LAYOUT_GENERAL,vkabi::VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL,0,vkabi::VK_ACCESS_TRANSFER_WRITE_BIT);}else{before[0]=barrier(swap,vkabi::VK_IMAGE_LAYOUT_PRESENT_SRC_KHR,vkabi::VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL,0,vkabi::VK_ACCESS_TRANSFER_WRITE_BIT);before[1]=barrier(interopImage_,vkabi::VK_IMAGE_LAYOUT_GENERAL,vkabi::VK_IMAGE_LAYOUT_TRANSFER_SRC_OPTIMAL,0,vkabi::VK_ACCESS_TRANSFER_READ_BIT);}
    vk_.vkCmdPipelineBarrier(commandBuffer_,vkabi::VK_PIPELINE_STAGE_TRANSFER_BIT,vkabi::VK_PIPELINE_STAGE_TRANSFER_BIT,0,0,nullptr,0,nullptr,(std::uint32_t)before.size(),before.data());vkabi::VkImageCopy region{};region.srcSubresource={vkabi::VK_IMAGE_ASPECT_COLOR_BIT,0,0,1};region.dstSubresource={vkabi::VK_IMAGE_ASPECT_COLOR_BIT,0,0,1};region.extent={swapDesc_.imageExtent.width,swapDesc_.imageExtent.height,1};if(intoCanonical)vk_.vkCmdCopyImage(commandBuffer_,swap,vkabi::VK_IMAGE_LAYOUT_TRANSFER_SRC_OPTIMAL,interopImage_,vkabi::VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL,1,&region);else vk_.vkCmdCopyImage(commandBuffer_,interopImage_,vkabi::VK_IMAGE_LAYOUT_TRANSFER_SRC_OPTIMAL,swap,vkabi::VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL,1,&region);
    if(intoCanonical){after[0]=barrier(swap,vkabi::VK_IMAGE_LAYOUT_TRANSFER_SRC_OPTIMAL,vkabi::VK_IMAGE_LAYOUT_PRESENT_SRC_KHR,vkabi::VK_ACCESS_TRANSFER_READ_BIT,0);after[1]=barrier(interopImage_,vkabi::VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL,vkabi::VK_IMAGE_LAYOUT_GENERAL,vkabi::VK_ACCESS_TRANSFER_WRITE_BIT,0);}else{after[0]=barrier(swap,vkabi::VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL,vkabi::VK_IMAGE_LAYOUT_PRESENT_SRC_KHR,vkabi::VK_ACCESS_TRANSFER_WRITE_BIT,0);after[1]=barrier(interopImage_,vkabi::VK_IMAGE_LAYOUT_TRANSFER_SRC_OPTIMAL,vkabi::VK_IMAGE_LAYOUT_GENERAL,vkabi::VK_ACCESS_TRANSFER_READ_BIT,0);}
    vk_.vkCmdPipelineBarrier(commandBuffer_,vkabi::VK_PIPELINE_STAGE_TRANSFER_BIT,vkabi::VK_PIPELINE_STAGE_TRANSFER_BIT,0,0,nullptr,0,nullptr,(std::uint32_t)after.size(),after.data());if(vk_.vkEndCommandBuffer(commandBuffer_)!=vkabi::VK_SUCCESS){fail(status,L"Vulkan compatibility could not end its copy command buffer");return false;}
    vkabi::VkSubmitInfo submit{};submit.sType=vkabi::VK_STRUCTURE_TYPE_SUBMIT_INFO;submit.commandBufferCount=1;submit.pCommandBuffers=&commandBuffer_;if(intoCanonical){submit.waitSemaphoreCount=(std::uint32_t)pendingWaits_.size();submit.pWaitSemaphores=pendingWaits_.empty()?nullptr:pendingWaits_.data();submit.pWaitDstStageMask=pendingWaitStages_.empty()?nullptr:pendingWaitStages_.data();}else{submit.signalSemaphoreCount=1;submit.pSignalSemaphores=&postSemaphore_;}
    if(vk_.vkQueueSubmit(queue_,1,&submit,vkabi::VK_NULL_HANDLE)!=vkabi::VK_SUCCESS){fail(status,L"Vulkan compatibility queue submission failed");return false;}if(intoCanonical){originalWaitsConsumed_=true;if(vk_.vkQueueWaitIdle(queue_)!=vkabi::VK_SUCCESS){fail(status,L"Vulkan compatibility could not synchronize the pre-neural copy");return false;}}else postCopySubmitted_=true;return true;
}

bool VulkanFrontend::waitForD3D11(RuntimeStatus& status){if(!completionQuery_)return true;d11Context_->End(completionQuery_.Get());d11Context_->Flush();const auto deadline=std::chrono::steady_clock::now()+std::chrono::seconds(2);BOOL complete=FALSE;while(std::chrono::steady_clock::now()<deadline){const auto hr=d11Context_->GetData(completionQuery_.Get(),&complete,sizeof(complete),D3D11_ASYNC_GETDATA_DONOTFLUSH);if(hr==S_OK&&complete)return true;if(FAILED(hr)){fail(status,L"Vulkan compatibility D3D11 completion query failed");return false;}std::this_thread::yield();}fail(status,L"Vulkan compatibility timed out waiting for D3D11 processing to finish");return false;}

bool VulkanFrontend::beginFrame(CompatFrame& frame,RuntimeStatus& status){if(!initialized_||!canonical_||!submitCopy(true,status))return false;frame.color=canonical_.Get();frame.width=swapDesc_.imageExtent.width;frame.height=swapDesc_.imageExtent.height;frame.format=dxgiFormat();frame.generation=generation_;frame.legacyCopies=0;status.api=GraphicsApi::Vulkan;status.rendererRoute=RendererRoute::CompatVulkan;status.compatInterop=CompatInterop::VulkanExternalMemory;wcscpy_s(status.message,L"Vulkan full-resolution external-memory frame acquired");return true;}
bool VulkanFrontend::endFrame(const CompatFrame&,RuntimeStatus& status){if(!waitForD3D11(status))return false;return submitCopy(false,status);}

void VulkanFrontend::destroyVulkanObjects(){if(device_){if(postSemaphore_&&vk_.vkDestroySemaphore)vk_.vkDestroySemaphore(device_,postSemaphore_,nullptr);if(commandPool_&&vk_.vkDestroyCommandPool)vk_.vkDestroyCommandPool(device_,commandPool_,nullptr);if(interopImage_&&vk_.vkDestroyImage)vk_.vkDestroyImage(device_,interopImage_,nullptr);if(interopMemory_&&vk_.vkFreeMemory)vk_.vkFreeMemory(device_,interopMemory_,nullptr);}postSemaphore_=0;commandPool_=0;commandBuffer_=nullptr;interopImage_=0;interopMemory_=0;}
void VulkanFrontend::reset(){destroyVulkanObjects();completionQuery_.Reset();canonical_.Reset();d11Context_.Reset();d11_.Reset();physical_=nullptr;device_=nullptr;queue_=nullptr;queueFamily_=imageIndex_=0;swapDesc_={};swapchainImages_.clear();pendingWaits_.clear();pendingWaitStages_.clear();pendingPresent_={};gipa_=nullptr;gdpa_=nullptr;vk_={};vkGetPhysicalDeviceImageFormatProperties2_=nullptr;vkGetPhysicalDeviceProperties2_=nullptr;vkGetPhysicalDeviceMemoryProperties_=nullptr;memoryProps_={};initialized_=false;originalWaitsConsumed_=postCopySubmitted_=false;}

} // namespace udlss::compat
